### ISSUE TITLE
GROUP BY gets marked as an error

### ISSUE THREAD

**Issue by gbirke** [gniezen/n3pygments#10]
GROUP BY in SPARQL queries gets  marked as an error.  Here is an example:

```sparql
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX vivo: <http://vivoweb.org/ontology/core#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (SAMPLE(?olabel) as ?organization_name) (COUNT(?org) as ?num_people)
WHERE {
    ?p        a             foaf:Person .
    ?relation vivo:relates  ?p, ?org .
    ?org      a             foaf:Organization ;
              rdfs:label    ?olabel .
}
GROUP BY ?org
```

**Comment by gbirke** [comment]
I'm sorry, that must have been the old pygments package (version 1.6) that came with my linux distribution. When I created a virtualenv and installed Pygments 2.0.2, the code was highlighted flawlessly.

Maybe you can put a minimum version requirement for Pygments in your setup.py

Thanx for the fast reply and your great library!

**Comment by gniezen** [comment]
No worries, I'll put a note in the README that 1.6 doesn't work.
