### ISSUE TITLE
Hyphens in Turtle prefixes cause weird behaviour

### ISSUE THREAD

**Issue by kaefer3000** [gniezen/n3pygments#7]
Hi,

when I have a hyphen in the prefix, then weird things happen to the @ character and the colouring of the rest of the line, see the following picture:

![hyphen in n3pygments](https://cloud.githubusercontent.com/assets/6708974/5460322/60a78756-8540-11e4-9df6-513f4994c723.png)

Cheers,

kaefer3000

**Comment by gniezen** [comment]
I've merged this into master, and will create a new issue to see that we better adhere to the latest specs.
