### ISSUE TITLE
Full (and hash) URIs cause trouble

### ISSUE THREAD

**Issue by kaefer3000** [gniezen/n3pygments#9]
Hi, I've found some more issues (using swlexer via pygments/minted in LaTeX):

    <http://ex.org/foo#bar> :foo : bar .
    :foo a :bar .

* the `org` in the URI is highlighted
* the `#` in the URI is treated as a comment-starting hash (screwing up the following line, too)

**Comment by gniezen** [comment]
I'm not seeing the same behaviour when using pygments/minted in LaTeX?

![screen shot 2015-01-26 at 14 51 18](https://cloud.githubusercontent.com/assets/418233/5901528/128ef8e2-a56b-11e4-826a-27b917fe9038.png)

**Comment by kaefer3000** [comment]
\documentclass{article}\usepackage{minted}
    \begin{document}\begin{minted}{turtle}
    <http://ex.org/foo#bar> :foo : bar .
    :foo a :bar .
    \end{minted}\end{document}
results in 
![swlexer](https://cloud.githubusercontent.com/assets/6708974/5901870/0d8aace6-a576-11e4-88f0-bf5f6f03a649.png)
I'm using giezen/n3pygments@5a7534978981d5b62af8c54294149427ee8e7fa0 (swlexers-0.3) and pygments

**Comment by gniezen** [comment]
Ah, the machine I'm using wasn't running the latest version of n3pygments, sorry. It seems we introduced this regression with #7. I've created a new branch hash-fix (which uses the older, stricter code), would you mind testing it as well and see if the rest of the functionality still works?

**Comment by kaefer3000** [comment]
Hi, thanks, close to perfect :-)
before:
![swlexer-before](https://cloud.githubusercontent.com/assets/6708974/5919860/0919c706-a638-11e4-9230-7d8abfdc15d4.png)
after:
![swlexer-after](https://cloud.githubusercontent.com/assets/6708974/5919879/1e6edfc4-a638-11e4-900e-dfb6833fcd7c.png)

**Comment by gniezen** [comment]
For `@prefix` I think a colon is required, i.e.

    @prefix ab-cd: <http://ex.org/ab-cd/> .

**Comment by kaefer3000** [comment]
Sorry you're right. Then it works. Thanks!!

**Comment by gniezen** [comment]
Great, I'll merge the changes into the master branch.
